name: Build & Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1️ Clona o repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️ Configura Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.23

      # 3️ Instala dependências
      - name: Install dependencies
        run: bun install --no-cache

      # 4️ Garante os tipos Node
      - name: Ensure Node types
        run: bun add -d @types/node

      # 5️ Rodar type-check
      - name: Type check
        run: bun tsc --noEmit -p tsconfig.json

      # 6️ Limpa builds antigos (substituindo rimraf)
      - name: Clean dist
        run: rm -rf dist

      # 7️ Build do projeto (gera a pasta dist)
      - name: Build project
        run: bun vite build

      # 8️ Prepara os arquivos para GitHub Pages
      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # 9️ Publica no GitHub Pages
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
